# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.


[[constraint]]
  name = "github.com/artyom/autoflags"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  branch = "master"
  name = "github.com/roundpartner/go"

[[constraint]]
  name = "github.com/stripe/stripe-go"
  version = "61.13.0"

[prune]
  go-tests = true
  unused-packages = true
